version: 2

groups:
  mkdocs:
    patterns:
    - "squidfunk/mkdocs-material"
    - "mkdocs-material"

updates:
  - package-ecosystem: docker
    directories:
      - "/.devcontainer"
      - "/docs"
    labels: [ ]
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directories:
      - "/"
    labels: [ ]
    schedule:
      interval: daily

  - package-ecosystem: pip
    directories:
      - "/docs"
    labels: [ ]
    schedule:
      interval: daily
    ignore:
      - dependency-name: "mike"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: npm
    directories:
      - "/"
    labels: [ ]
    schedule:
      interval: daily
    versioning-strategy: increase
    ignore:
      - dependency-name: "@middy/core"
        update-types: [ "version-update:semver-major" ]
    groups:
      aws-sdk-v3:
        patterns:
        - "@aws-sdk/*"
        - "@smithy/*"
        - "aws-sdk-client-mock"
        - "aws-sdk-client-mock-jest"
      aws-cdk:
        patterns:
        - "@aws-cdk/cli-lib-alpha"
        - "aws-cdk-lib"
        - "aws-cdk"
      typedoc:
        patterns:
        - "typedoc"
        - "typedoc-plugin-*"
